### PR TITLE
DM-25102: Distribute lsst/alert_stream on PyPI

### PR DESCRIPTION
**Pull request by spenczar**
#### Ticket:
[DM-25102](https://jira.lsstcorp.org/browse/DM-25102)

This follows the patterns set in [DM-25199](https://github.com/lsst/alert_packet/pull/15) over in alert_packet.

That PR caused issues ([DM-25280](https://jira.lsstcorp.org/browse/DM-25280)) because the use of Python setuptools clashed with our previous EUPS-based way of integrating the package into the stack. I don't think this PR will have the same issues because this package is never used in the LSST stack. It doesn't have any EUPS configuration for installation.

### CODE REVIEW

**Review by jdswinbank — APPROVED** [review]
Since you are moving the scripts out of `bin` and providing entry points instead, you could remove the `if __name__ == "__main__"` stuff from them, just for neatness.

Otherwise, looks good to me. 👍

**Comment by stedrew** [comment]
@spenczar FYI, this effectively broke the image and made all docs obsolete. Came here from [this guide](https://mtpatter.github.io/bilao/notebooks/html/01-spark-struct-stream-kafka.html) to learn spark structured streaming but nothing works.

**Comment by jdswinbank** [comment]
Hi @zhuheec — sorry about that! This code is still very much under development, and I'm afraid we can't guarantee interface stability for now. Unfortunately, the guide you linked to is not something maintained by our project, so we can't do anything directly to fix it.

@mtpatter (Hi!) — do you have time/inclination to update that notebook? Or perhaps it'd be worth just adding a disclaimer to it that it's not up-to-date with the latest version of the Rubin/LSST code? Thanks!

**Comment by spenczar** [comment]
@zhuheec, a lot of the Docker infrastructure here has been subsumed by https://github.com/lsst-dm/alert-stream-simulator. Maybe we should clean out the Dockerfile and compose scripts in this repo to clarify that; this is moving towards becoming a package that will actually get used by the LSST stack, rather than a demonstration or standalone tool.

You might have more luck using alert-stream-simulator to generate data, but I can't promise that any of the rest of that tutorial will make sense. For one thing, the schema of alert packets has been changed.

**Comment by mtpatter** [comment]
(Hi!)  I can try the new simulator and if it makes sense will update that notebook and if not will make a note and put it on my todo list.  @zhuheec think that spark structured streaming notebook is three years old, so the tutorial might not be a good representation of current status for anything, but you could also try my Docker image from a while back if that is useful. https://hub.docker.com/repository/docker/mtpatter/alert_stream

**Comment by jdswinbank** [comment]
Thanks @mtpatter  :-)

**Pull request merged**
