### PR TITLE
New and updated schemas recently added in the sample-avro-alert repo (DM-16280)

### PR DESCRIPTION
**Pull request by JulienPeloton**
Hi,

## Context 
In the last PR (#20), the Dockerfile was modified to pull the master branch of [sample-avro-alert](https://github.com/lsst-dm/sample-avro-alert) instead of another (merged) branch.

However, in between this previous used branch and the current master of the [sample-avro-alert](https://github.com/lsst-dm/sample-avro-alert) repo, another PR was merged with several modifications (see [PR:DM-16280](https://github.com/lsst-dm/sample-avro-alert/pull/4)). These new changes unfortunately break the functioning of this repo (my bad, I should have seen it earlier...).

## New Schemas

[PR:DM-16280](https://github.com/lsst-dm/sample-avro-alert/pull/4) introduced new schemas. I have modified schemas to comply with it (see https://github.com/lsst-dm/alert_stream/commit/2e32bf13ca8ed72e8fe8a400497fdf0e136a59d6):

```python
# in bin/sendAlertStream.py
schema_files = [
  "../sample-avro-alert/schema/diasource.avsc",
  "../sample-avro-alert/schema/diaforcedsource.avsc", 
  "../sample-avro-alert/schema/dianondetectionlimit.avsc",
  "../sample-avro-alert/schema/diaobject.avsc",
  "../sample-avro-alert/schema/ssobject.avsc",
  "../sample-avro-alert/schema/cutout.avsc",
  "../sample-avro-alert/schema/alert.avsc"]
```

## Modifications of values in schemas
 
Unfortunately, not only new schemas were introduced but values in existing ones were also modified.
Hence the data provided in this repo is no more valid. Example, if I want to produce an alert stream:
```bash
docker run -it --rm \     
  --network=alert_stream_default \
  -v $PWD/data:/home/alert_stream/data:ro alert_stream \
  python bin/sendAlertStream.py kafka:9092 my-stream

visit: 1574. 	time: 1548757977.0034723
Task exception was never retrieved
future: <Task finished coro=<schedule_delays() done, defined at bin/sendAlertStream.py:29> exception=ValueError('no value and no default for programId',)>
Traceback (most recent call last):
  File "bin/sendAlertStream.py", line 46, in schedule_delays
    yield from asyncio.ensure_future(delay(wait_time, function, arg))
  File "bin/sendAlertStream.py", line 26, in delay
    return function(*args)
  File "bin/sendAlertStream.py", line 89, in send_visit
    streamProducer.send(record, encode=True)
  File "/home/alert_stream/python/lsst/alert/stream/alertProducer.py", line 38, in send
    avro_bytes = avroUtils.writeAvroData(data, self.alert_schema)
  File "/home/alert_stream/python/lsst/alert/stream/avroUtils.py", line 59, in writeAvroData
    fastavro.schemaless_writer(bytes_io, json_schema, json_data)
  File "fastavro/_write.pyx", line 731, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 537, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 474, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 537, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 473, in fastavro._write.write_record
ValueError: no value and no default for programId
```

The `programId` key is for example such a new value introduced. 

## What else should be done?

My feeling is that data in this repo needs to be reprocessed with the (new+updated) schemas from the [sample-avro-alert](https://github.com/lsst-dm/sample-avro-alert) repo. What do you think? If so, how can I re-generate this data to test this?

### CODE REVIEW

**Comment by jdswinbank** [comment]
Hi @JulienPeloton — thanks for following up on this. I confirm the error that you are seeing.

You've sent me off down a rabbit hole of understanding Avro schema evolution today. I'll update this ticket with more information when I have it.

**Comment by jdswinbank** [comment]
I plan to tackle this on [DM-17551](https://jira.lsstcorp.org/browse/DM-17551).

**Comment by JulienPeloton** [comment]
@jdswinbank thanks for taking care of this! 

I do not know what is the status (private, open source?) of the "alert file simulator" (i.e. the tool that generates the alert in avro files for a given schema), but if possible it would be good to have access to it, so that one can regenerate the files by ourself, and one can also generate more than 4 files if needed.

**Comment by jdswinbank** [comment]
Hi @JulienPeloton —

Unfortunately, the getting access to the alert simulator is not quite so easy as you might hope.

The original simulation was carried out by the LSST Sims group. The results of that were extracted and provided to us in the form of an SQLite database. That database isn't currently available on the web, but it's possible that we could fix that.

When you've got that database, the scripts at https://github.com/lsst/sims_catUtils/blob/master/python/lsst/sims/catUtils/utils/avroAlertGenerator.py and https://github.com/lsst/sims_catUtils/blob/master/examples/alertSimulation/generate_avro_alerts.py were used to turn it into the Avro files included in this package. I've not read those carefully, but from a quick look they have baked-in assumptions about the structure of the old schema.

Rather than re-creating this whole process, depending on your use case it's worth considering:

- Converting the old Avro packets to the new schema is likely easier than recreating them from the SQLite database. I'll do this (but I haven't had time to yet; sorry); I'll also try to make sure this happens easily/automatically in future.
- Generating large quantities of alerts packets e.g. for scale testing would probably be most easily done by simply populating the schema with random numbers, rather than linking back to a realistic simulation.

However, there are certainly use cases that neither of those options will satisfy. My colleague @ebellm might be the best person to talk to about how we can best help you meet your particular goals.

**Comment by JulienPeloton** [comment]
Thanks @jdswinbank for the detailed explanations - I did not realise the data alerts here were extracted from a more complex pipeline (actually there are many None!).

> That database isn't currently available on the web, but it's possible that we could fix that.

Let me know when this goes live!

> Converting the old Avro packets to the new schema [...]

Yes short-term, I think this is the easiest option. I can also have a look at the conversion if you cannot put time on this (say before the end of the next week). Ideally, my goal would be to have the repo up-to-date before the DESC Broker workshop at the end of the month.

> Generating large quantities of alerts packets e.g. for scale testing would probably be most easily by simply populating the schema with random numbers

For pure scaling (i.e. amount of data that can be handled) yes - but of course that would not be very useful to predict the behaviour of a particular filter set in realistic conditions, nor test effects that rely on long timescales (correlated alerts) - which is what I want to test for a broker.

Thanks!

**Comment by ebellm** [comment]
@JulienPeloton I'd suggest we have a more detailed conversation offline about your goals. I don't think the simulated inputs to the sample packets provided here are going to be very meaningful scientifically; as you saw they are mostly empty, as they were developed for scale testing.  

If your goal is to develop experience with filtering on realistic alerts I'd strongly encourage you to take a look at the ZTF alerts (https://ztf.uw.edu/alerts/public/).  There are significant differences in schema content (as well as the nature of the input data, of course), but the conceptual foundations are the same and it's real data.

Finally I'll note that I expect us to start producing alert packets with the LSST pipelines in the intermediate term--I hope later this year--so that would give you alerts in our current best-guess LSST schema based on real input data from e.g. DECam and HSC.

**Comment by ebellm** [comment]
I will also note that the sample alerts currently in `data/` have the schemas embedded in them, so I think we could more easily avoid this problem by removing the optional `schema_files` argument in the construction of `streamProducer` (https://github.com/lsst-dm/alert_stream/blob/2e32bf13ca8ed72e8fe8a400497fdf0e136a59d6/bin/sendAlertStream.py#L72).  

I haven't yet checked if there is further trouble downstream; the functions used throughout this package make sometimes inconsistent assumptions about where to obtain the schemas.

**Comment by JulienPeloton** [comment]
Thanks @ebellm for suggestions! 

> If your goal is to develop experience with filtering on realistic alerts I'd strongly encourage you to take a look at the ZTF alerts (https://ztf.uw.edu/alerts/public/). There are significant differences in schema content (as well as the nature of the input data, of course), but the conceptual foundations are the same and it's real data.

I looked at the ZTF public alerts, and they are indeed perfect for designing a broker - numerous & meaningful!

> I will also note that the sample alerts currently in data/ have the schemas embedded in them, so I think we could more easily avoid this problem by removing the optional schema_files argument in the construction of streamProducer

Good catch - with very few modifications I could get the script to work without specifying the schemas. I can submit this patch if you think it would be better suited to this repo.

**Comment by jdswinbank** [comment]
> I will also note that the sample alerts currently in data/ have the schemas embedded in them, so I think we could more easily avoid this problem by removing the optional schema_files argument...

Right — one of the reasons I've been slow getting to grips with this is that I wanted to properly rethink the code here so that we're only using schemata when necessary and passing them along in a consistent way.

I'll try and get to grips with that shortly. If I get distracted and then can't do so, I'm happy for @JulienPeloton to put in a quick patch to just get things working for now.

**Comment by JulienPeloton** [comment]
OK @jdswinbank, I will wait for your inputs then. Thanks!

**Comment by jdswinbank** [comment]
@JulienPeloton — I believe the combination of https://github.com/lsst-dm/alert_stream/pull/22 and https://github.com/lsst-dm/sample-avro-alert/pull/5 will address your requests. Comments and feedback welcome!

**Comment by jdswinbank** [comment]
I think we can close this PR given the discussion on #22. @JulienPeloton, please reopen if you disagree.

**Pull request closed without merging**
